### PR TITLE
up compat to support Makie 0.19

### PR DESCRIPTION
**Pull request by lazarusA**
As a key player in BeautifulMakie, where at least AoG, GeoMakie and Makie  need to be compatible all the time I'm submitting this PR 😄

### CODE REVIEW

**Comment by lazarusA** [comment]
Oh, not that simple. This [function](https://github.com/MakieOrg/GeoMakie.jl/blob/d9404ac664bfe99eaffb55441737f4ed9df4cf46/src/utils.jl#L231) is completely broke.

**Comment by haakon-e** [comment]
Locally, I was able to get all tests passing with the changes outlined below.

Replace:
https://github.com/MakieOrg/GeoMakie.jl/blob/26eadac28c523917be3468d8b1d322e7a94373ce/src/utils.jl#L231-L234
by:
```julia
function text_bbox(textstring::AbstractString, fontsize::Union{AbstractVector, Number}, font, fonts, align, rotation, justification, lineheight)
    glyph_collection = Makie.layout_text(
            textstring, fontsize,
            string(font), fonts, align, rotation, justification, lineheight,
```
* This was necessary since support for `:Symbol` in `to_font` was removed in https://github.com/MakieOrg/Makie.jl/pull/2321 [[link to diff](https://github.com/MakieOrg/Makie.jl/pull/2321/files#diff-319f6895319eb78578eb8091872ce5a2188ab92504cc10cc987b34978bf1a8dbL923-L924)]
* Note: I'm not sufficiently familiar with `Makie` internals to understand what is the "proper" approach to resolving `font`.

Replace:
https://github.com/MakieOrg/GeoMakie.jl/blob/26eadac28c523917be3468d8b1d322e7a94373ce/src/utils.jl#L281-L284
by:
```julia
# We have computed the normal vector - now we have to get tick extents 
fonts = theme(scene, :fonts)
extents = text_bbox(
    ticklabel, ticksize,
    tickfont, fonts, Vec2f(0), tickrotation,
```
* here I simply fetch the `:fonts` from the scene theme. 
-----
I'm not sure if it's related, but the [Italy's states](https://geo.makie.org/stable/examples/#Italy's-states) example looks very weird locally. The lines in the png-version is all over the place (see below), and the `.pdf` version is completely broken for me (I'm unable to open the file, see below):
#### png:
image
#### pdf:
image

**Comment by lazarusA** [comment]
maybe this is something that @jkrumbiegel  can spot in a second. I, on the other hand I'm overwhelm by all the new changes to `layout_text(rt::RichText,...)` , and doing the changes suggested above don't work for me :(

**Comment by haakon-e** [comment]
> maybe this is something that @jkrumbiegel can spot in a second. I, on the other hand I'm overwhelm by all the new changes to `layout_text(rt::RichText,...)` , and doing the changes suggested above don't work for me :(

Here's a branch with the changes that pass locally for me: https://github.com/haakon-e/GeoMakie.jl/tree/up_compat

**Comment by lazarusA** [comment]
Try a PR to GeoMakie 😉

**Comment by haakon-e** [comment]
ahah, sure! I just didn't want to step on any toes! #142

**Pull request closed without merging**
